<a href="https://colab.research.google.com/github/AlexitoFernandez/practicas-google-colab/blob/unidad-3/Pr%C3%A1ctica_1_KNN_Frutas.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

#"Machine Learning"
##Unidad III
### **Practica 1 - Algortimo K-NN, los K-Vecinos mas Cercanos**

Alumno: Jorge Alejandro Fernández De Los Santos.

Facilitador: José Gabriel Rodríguez Rivas.

In [14]:
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
import seaborn as sns
from sklearn.model_selection import train_test_split
from sklearn.neighbors import KNeighborsRegressor, KNeighborsClassifier
from sklearn.metrics import classification_report, confusion_matrix
from sklearn.inspection import permutation_importance
from sklearn.preprocessing import StandardScaler
import gdown
import plotly.express as px

# Cargar el dataset
url = 'https://drive.google.com/uc?id=1RB2NkqhkAV_q0YuQ85Hw9QP_sRPZF4sE'
output = 'fruit_data_with_colors.csv'
gdown.download(url, output, quiet=False)
frutas = pd.read_csv(output)
print(frutas.head())

Downloading...
From: https://drive.google.com/uc?id=1RB2NkqhkAV_q0YuQ85Hw9QP_sRPZF4sE
To: /content/fruit_data_with_colors.csv
100%|██████████| 2.34k/2.34k [00:00<00:00, 12.0MB/s]

   fruit_label fruit_name fruit_subtype  mass  width  height  color_score
0            1      apple  granny_smith   192    8.4     7.3         0.55
1            1      apple  granny_smith   180    8.0     6.8         0.59
2            1      apple  granny_smith   176    7.4     7.2         0.60
3            2   mandarin      mandarin    86    6.2     4.7         0.80
4            2   mandarin      mandarin    84    6.0     4.6         0.79


In [5]:
# Selección de variables predictoras (x) y variable a predecir (y)
X = frutas[["height", "width", "mass", "color_score"]]
y = frutas["fruit_name"]

In [6]:
# Se divide dataset en conjunto de entrenamiento y prueba
X_train, X_test, y_train, y_test = train_test_split(X, y, random_state=42)

In [10]:
#Se define el clasificador KNN con 1 vecino
clasificador_KNN = KNeighborsClassifier(n_neighbors= 1)

In [11]:
#Se realiza el entrenamiento con las variables definidas
clasificador_KNN.fit(X_train, y_train)
print("Precision del clasificador en fase de entrenamiento",
clasificador_KNN.score(X_train, y_train) )

Precision del clasificador en fase de entrenamiento 1.0


In [12]:
# Evaluación del modelo k=1
print("Precision del clasificador en fase de entrenamiento", clasificador_KNN.score(X_train, y_train))
y_pred = clasificador_KNN.predict(X_test)
print("Reporte de métricas del clasificador: \n", classification_report(y_test, y_pred))
print("Precisión:", clasificador_KNN.score(X_test, y_test))
print("Matriz de confusión: \n", confusion_matrix(y_test, y_pred), "\n")

Precision del clasificador en fase de entrenamiento 1.0
Reporte de métricas del clasificador: 
               precision    recall  f1-score   support

       apple       0.00      0.00      0.00         4
       lemon       1.00      0.60      0.75         5
    mandarin       1.00      1.00      1.00         2
      orange       0.38      0.75      0.50         4

    accuracy                           0.53        15
   macro avg       0.59      0.59      0.56        15
weighted avg       0.57      0.53      0.52        15

Precisión: 0.5333333333333333
Matriz de confusión: 
 [[0 0 0 4]
 [1 3 0 1]
 [0 0 2 0]
 [1 0 0 3]] 



In [15]:
# Calcular Permutation Importance (evalúa cuánto empeora el rendimiento del modelo cuando se altera aleatoriamente una característica)
result = permutation_importance(clasificador_KNN, X_test, y_test, n_repeats=30, random_state=42)
importancia = pd.DataFrame({
    "Variable": X.columns,
    "Importancia Media": result.importances_mean,
    "Desviación": result.importances_std
}).sort_values("Importancia Media", ascending=False)
print(importancia)

# Visualizar con Plotly
fig4 = px.bar(importancia, x="Variable", y="Importancia Media",
             error_y="Desviación", title="Importancia de características (KNN - Permutation Importance)",
             text_auto=".3f", color="Variable")
fig4.update_layout(width=600, height=400)
fig4.show()

      Variable  Importancia Media  Desviación
2         mass           0.266667    0.095839
3  color_score          -0.004444    0.016630
0       height          -0.028889    0.063674
1        width          -0.062222    0.048483


In [26]:
# Modelo con k=3
clasificador_KNN3 = KNeighborsClassifier(n_neighbors=3)
clasificador_KNN3.fit(X_train, y_train)
y_pred3 = clasificador_KNN3.predict(X_test)
print("Precision entrenamiento k=3:", clasificador_KNN3.score(X_train, y_train))
print("Reporte k=3:\n", classification_report(y_test, y_pred3))
print("Precisión k=3:", clasificador_KNN3.score(X_test, y_test))
# Resumen de las predicciones realizadas por el clasificador
print ("Matriz de confusión:\n", confusion_matrix(y_test, y_pred3), "\n")

Precision entrenamiento k=3: 0.8409090909090909
Reporte k=3:
               precision    recall  f1-score   support

       apple       0.67      0.50      0.57         4
       lemon       0.50      0.40      0.44         5
    mandarin       1.00      1.00      1.00         2
      orange       0.50      0.75      0.60         4

    accuracy                           0.60        15
   macro avg       0.67      0.66      0.65        15
weighted avg       0.61      0.60      0.59        15

Precisión k=3: 0.6
Matriz de confusión:
 [[2 1 0 1]
 [1 2 0 2]
 [0 0 2 0]
 [0 1 0 3]] 



In [27]:
# Modelo con k=5
clasificador_KNN5 = KNeighborsClassifier(n_neighbors=5)
clasificador_KNN5.fit(X_train, y_train)
y_pred5 = clasificador_KNN5.predict(X_test)
print("Precision entrenamiento k=5:", clasificador_KNN5.score(X_train, y_train))
print("Reporte k=5:\n", classification_report(y_test, y_pred5))
print("Precisión k=5:", clasificador_KNN5.score(X_test, y_test))
# Resumen de las predicciones realizadas por el clasificador
print("Matriz de confusión:\n", confusion_matrix(y_test, y_pred5),"\n")

Precision entrenamiento k=5: 0.8181818181818182
Reporte k=5:
               precision    recall  f1-score   support

       apple       0.67      0.50      0.57         4
       lemon       0.50      0.40      0.44         5
    mandarin       1.00      1.00      1.00         2
      orange       0.50      0.75      0.60         4

    accuracy                           0.60        15
   macro avg       0.67      0.66      0.65        15
weighted avg       0.61      0.60      0.59        15

Precisión k=5: 0.6
Matriz de confusión:
 [[2 1 0 1]
 [1 2 0 2]
 [0 0 2 0]
 [0 1 0 3]] 



In [28]:
# Probar distintos valores de k
for k in range(1, 20):
    knn = KNeighborsClassifier(n_neighbors=k)
    knn.fit(X_train, y_train)
    print(f"k={k} Precisión: {knn.score(X_test, y_test):.2f}")

k=1 Precisión: 0.53
k=2 Precisión: 0.53
k=3 Precisión: 0.60
k=4 Precisión: 0.60
k=5 Precisión: 0.60
k=6 Precisión: 0.40
k=7 Precisión: 0.60
k=8 Precisión: 0.53
k=9 Precisión: 0.53
k=10 Precisión: 0.53
k=11 Precisión: 0.47
k=12 Precisión: 0.47
k=13 Precisión: 0.47
k=14 Precisión: 0.47
k=15 Precisión: 0.40
k=16 Precisión: 0.40
k=17 Precisión: 0.40
k=18 Precisión: 0.47
k=19 Precisión: 0.40


In [29]:
# Preparación con escalado
X = frutas[["height", "width", "mass", "color_score"]]
y = frutas["fruit_name"]

# División con estratificación
X_train, X_test, y_train, y_test = train_test_split(X, y, random_state=42, stratify=y)

# Normalización
scaler = StandardScaler()
X_train_scaled = scaler.fit_transform(X_train)
X_test_scaled = scaler.transform(X_test)

# Entrenamiento y evaluación del modelo escalado (k=3)
knn_scaled = KNeighborsClassifier(n_neighbors=3)
knn_scaled.fit(X_train_scaled, y_train)
y_pred_scaled = knn_scaled.predict(X_test_scaled)

print("\nReporte de clasificación (Escalado):")
print(classification_report(y_test, y_pred_scaled))
print("Matriz de confusión (Escalado): \n", confusion_matrix(y_test, y_pred_scaled))


Reporte de clasificación (Escalado):
              precision    recall  f1-score   support

       apple       1.00      0.80      0.89         5
       lemon       1.00      1.00      1.00         4
    mandarin       1.00      1.00      1.00         1
      orange       0.83      1.00      0.91         5

    accuracy                           0.93        15
   macro avg       0.96      0.95      0.95        15
weighted avg       0.94      0.93      0.93        15

Matriz de confusión (Escalado): 
 [[4 0 0 1]
 [0 4 0 0]
 [0 0 1 0]
 [0 0 0 5]]


In [31]:
#Importancia de las variables despues del escalado
result = permutation_importance(knn_scaled, X_test_scaled, y_test, n_repeats=30, random_state=42)
importancia = pd.DataFrame({
"Variable": X.columns,
"Importancia Media": result.importances_mean,
"Desviación": result.importances_std
}).sort_values("Importancia Media", ascending=False)
print(importancia)

# Visualizar importancias con Plotly
fig4 = px.bar(importancia, x="Variable", y="Importancia Media",
             error_y="Desviación", title="Importancia de características (KNN - Permutation Importance)",
             text_auto=".3f", color="Variable")
fig4.update_layout(width=600, height=400)
fig4.show()

      Variable  Importancia Media  Desviación
0       height           0.262222    0.080615
1        width           0.188889    0.075195
3  color_score           0.182222    0.103184
2         mass           0.037778    0.061303


In [32]:
# Predicción de una sola fruta (altura, ancho, masa, escala de color)
fruta1 = [[5.5, 2.2, 150, 0.70]]
print("la fruta 1 es de tipo", knn_scaled.predict(fruta1))

# Predicción de múltiples frutas
nuevas_frutas = [[5.5, 2.2, 120, 0.70], [2, 2, 160, 0.50]]
print("las frutas son de tipo:", knn_scaled.predict(nuevas_frutas))

la fruta 1 es de tipo ['orange']
las frutas son de tipo: ['orange' 'orange']
