<a href="https://colab.research.google.com/github/AlexitoFernandez/practicas-google-colab/blob/unidad-3/Practica_3_KNN_LC.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

#"Machine Learning"
##Unidad III
### **Practica 3 - KNN Lending Club**

Alumno: Jorge Alejandro Fernández De Los Santos.

Facilitador: José Gabriel Rodríguez Rivas.

In [4]:
import numpy as np
import pandas as pd
import seaborn as sns
import matplotlib.pyplot as plt
import plotly.express as px
import plotly.graph_objects as go
from sklearn.neighbors import KNeighborsClassifier
from sklearn.model_selection import train_test_split
from sklearn.metrics import classification_report, confusion_matrix, precision_recall_curve
import gdown

# Carga de datos
file_id = '1HBU_efbbPg378pZvLZ1AtvRFAKrEFsob'
output = 'lending_club_2007_2011_6_states.csv'
gdown.download(id=file_id, output=output, quiet=False)
prestamos_df= pd.read_csv(output)
print(prestamos_df.head())

Downloading...
From: https://drive.google.com/uc?id=1HBU_efbbPg378pZvLZ1AtvRFAKrEFsob
To: /content/lending_club_2007_2011_6_states.csv
100%|██████████| 7.01M/7.01M [00:00<00:00, 75.1MB/s]


   loan_amnt  funded_amnt  funded_amnt_inv       term  int_rate  installment  \
0       2400         2400           2400.0  36 months     15.96        84.33   
1      10000        10000          10000.0  36 months     13.49       339.31   
2       3000         3000           3000.0  36 months     18.64       109.43   
3       5600         5600           5600.0  60 months     21.28       152.39   
4       5375         5375           5350.0  60 months     12.69       121.45   

  grade sub_grade            emp_title emp_length  ... application_type  \
0     C        C5                  NaN  10+ years  ...       Individual   
1     C        C1  AIR RESOURCES BOARD  10+ years  ...       Individual   
2     E        E1      MKC Accounting     9 years  ...       Individual   
3     F        F2                  NaN    4 years  ...       Individual   
4     B        B5            Starbucks   < 1 year  ...       Individual   

   acc_now_delinq chargeoff_within_12_mths delinq_amnt pub_rec_bankr

In [8]:
# Codificar columnas categóricas a numéricas
prestamos_df['grade_code'] = prestamos_df['grade'].astype('category').cat.codes
prestamos_df['purpose_code'] = prestamos_df['purpose'].astype('category').cat.codes
prestamos_df['addr_state_code'] = prestamos_df['addr_state'].astype('category').cat.codes
prestamos_df['home_ownership_code'] = prestamos_df['home_ownership'].astype('category').cat.codes

# Crear la columna 'repaid' a partir de 'loan_status'
# Asumiendo que 'loan_status' existe y 'Fully Paid' significa que el préstamo fue pagado.
prestamos_df['repaid'] = prestamos_df['loan_status'].apply(lambda status: 1 if status == 'Fully Paid' else 0)

# Definición de variables predictoras y objetivo
X = prestamos_df[['funded_amnt', "int_rate", "grade_code", 'purpose_code', 'addr_state_code', 'home_ownership_code', 'annual_inc', 'dti', 'revol_util', 'pub_rec_bankruptcies']]
y = prestamos_df["repaid"]

# Eliminar filas con valores NaN en X e y
# Se unen X e y temporalmente para asegurar que las mismas filas sean eliminadas de ambos
combined = pd.concat([X, y], axis=1).dropna()
X = combined.drop('repaid', axis=1)
y = combined['repaid']

# División en conjunto de entrenamiento y prueba
X_train, X_test, y_train, y_test = train_test_split(X, y, test_size=0.4, random_state=42)

In [11]:
# KNN con 1 vecino
# Creamoos el clasificador de regresion logistica
knn1 = KNeighborsClassifier(n_neighbors = 1)
# Entrenamos el clasificador
knn1.fit(X_train, y_train)
# Precisión del modelo en la fase de entrenamiento
print("Precision del clasificador en fase de entrenamiento", knn1.score(X_train, y_train) )

# Realizar una prediccion con los datos de prueba
y_pred = knn1.predict(X_test)
# Crear un informe de texto que muestre las principales métricas de clasificación.
print("\nReporte de métricas del clasificador con 5 vecinos: \n",
classification_report(y_test, y_pred, target_names=["No Pagado", "Pagado"]))
print(f'\nMatriz de Confusion con 5 vecinos:\n', confusion_matrix(y_test, y_pred ))

Precision del clasificador en fase de entrenamiento 1.0

Reporte de métricas del clasificador con 5 vecinos: 
               precision    recall  f1-score   support

   No Pagado       0.16      0.15      0.16      1181
      Pagado       0.85      0.86      0.86      6650

    accuracy                           0.76      7831
   macro avg       0.51      0.51      0.51      7831
weighted avg       0.75      0.76      0.75      7831


Matriz de Confusion con 5 vecinos:
 [[ 179 1002]
 [ 916 5734]]


In [13]:
# KNN con 5 vecinos
# Creamoos el clasificador de regresion logistica
knn5 = KNeighborsClassifier(n_neighbors = 5)
# Entrenamos el clasificador
knn5.fit(X_train, y_train)
# Precisión del modelo en la fase de entrenamiento
print("Precision del clasificador en fase de entrenamiento", knn5.score(X_train, y_train) )

# Realizar una prediccion con los datos de prueba
y_pred = knn5.predict(X_test)
# Crear un informe de texto que muestre las principales métricas de clasificación.
print("\nReporte de métricas del clasificador con 5 vecinos: \n",
classification_report(y_test, y_pred, target_names=["No Pagado", "Pagado"]))
print(f'\nMatriz de Confusion con 5 vecinos:\n', confusion_matrix(y_test, y_pred ))

Precision del clasificador en fase de entrenamiento 0.8622392507449979

Reporte de métricas del clasificador con 5 vecinos: 
               precision    recall  f1-score   support

   No Pagado       0.18      0.04      0.06      1181
      Pagado       0.85      0.97      0.91      6650

    accuracy                           0.83      7831
   macro avg       0.51      0.50      0.48      7831
weighted avg       0.75      0.83      0.78      7831


Matriz de Confusion con 5 vecinos:
 [[  43 1138]
 [ 198 6452]]


In [14]:
# KNN con 1 vecino
# Creamoos el clasificador de regresion logistica
knn10 = KNeighborsClassifier(n_neighbors = 10)
# Entrenamos el clasificador
knn10.fit(X_train, y_train)
# Precisión del modelo en la fase de entrenamiento
print("Precision del clasificador en fase de entrenamiento", knn10.score(X_train, y_train) )

# Realizar una prediccion con los datos de prueba
y_pred = knn10.predict(X_test)
# Crear un informe de texto que muestre las principales métricas de clasificación.
print("\nReporte de métricas del clasificador con 5 vecinos: \n",
classification_report(y_test, y_pred, target_names=["No Pagado", "Pagado"]))
print(f'\nMatriz de Confusion con 5 vecinos:\n', confusion_matrix(y_test, y_pred ))

Precision del clasificador en fase de entrenamiento 0.8568752660706683

Reporte de métricas del clasificador con 5 vecinos: 
               precision    recall  f1-score   support

   No Pagado       0.16      0.02      0.03      1181
      Pagado       0.85      0.99      0.91      6650

    accuracy                           0.84      7831
   macro avg       0.51      0.50      0.47      7831
weighted avg       0.75      0.84      0.78      7831


Matriz de Confusion con 5 vecinos:
 [[  19 1162]
 [  99 6551]]


In [15]:
from sklearn.inspection import permutation_importance
result = permutation_importance(knn10, X_test, y_test, n_repeats=30, random_state=42)
importancia = pd.DataFrame({
"Variable": X.columns,
"Importancia Media": result.importances_mean,
"Desviación": result.importances_std
}).sort_values("Importancia Media", ascending=False)
print(importancia)

               Variable  Importancia Media  Desviación
0           funded_amnt           0.003167    0.001289
6            annual_inc           0.002516    0.001308
9  pub_rec_bankruptcies           0.000000    0.000000
5   home_ownership_code           0.000000    0.000000
2            grade_code          -0.000094    0.000056
4       addr_state_code          -0.000098    0.000054
1              int_rate          -0.000179    0.000078
3          purpose_code          -0.000213    0.000133
7                   dti          -0.000417    0.000231
8            revol_util          -0.000745    0.000484


In [16]:
# Visualizar importancias con Plotly
import plotly.express as px
fig4 = px.bar(importancia, x="Variable", y="Importancia Media",
error_y="Desviación", title="Importancia de características (KNN - Permutation Importance)",
text_auto=".3f", color="Variable")
fig4.update_layout(width=800, height=600)
fig4.show()

In [25]:
#Normalización de los datos con StandardScaler
from sklearn.preprocessing import StandardScaler
X = prestamos_df[['funded_amnt', "int_rate", "grade_code", 'purpose_code', 'addr_state_code',
'home_ownership_code', 'annual_inc', 'dti', 'revol_util',
'pub_rec_bankruptcies']]
y = prestamos_df["repaid"]

# Eliminar filas con valores NaN en X e y ANTES de dividir y normalizar
combined = pd.concat([X, y], axis=1).dropna()
X = combined.drop('repaid', axis=1)
y = combined['repaid']

# Dividir Datos, stratify es para que mantenga la misma proporción de clases en ambos conjuntos
X_train, X_test, y_train, y_test = train_test_split(X, y, test_size=0.4, random_state=42, stratify=y)
# Normalizar variables (KNN es sensible a la escala)
scaler = StandardScaler()
X_train_scaled = scaler.fit_transform(X_train)
X_test_scaled = scaler.transform(X_test)

# 4. Modelo de Clasificación con datos normalizados y 1 vecino
knn_scaled = KNeighborsClassifier(n_neighbors=1)
knn_scaled.fit(X_train_scaled, y_train)
y_pred_scaled = knn_scaled.predict(X_test_scaled)

#Evaluación del modelo
print("\nReporte de clasificación datos normalizados:")
print(classification_report(y_test, y_pred_scaled, target_names=["No Pagado", "Pagado"]))
print("\nMatriz de confusión con datos normalizados:\n",
      confusion_matrix(y_test, y_pred_scaled), "\n")


Reporte de clasificación datos normalizados:
              precision    recall  f1-score   support

   No Pagado       0.20      0.22      0.21      1148
      Pagado       0.86      0.86      0.86      6683

    accuracy                           0.76      7831
   macro avg       0.53      0.54      0.53      7831
weighted avg       0.77      0.76      0.76      7831


Matriz de confusión con datos normalizados:
 [[ 247  901]
 [ 965 5718]] 



In [21]:
#Modelo de Clasificación con datos normalizados y 3 vecinos
knn_scaled = KNeighborsClassifier(n_neighbors=3)
knn_scaled.fit(X_train_scaled, y_train)
y_pred_scaled = knn_scaled.predict(X_test_scaled)
print("\nReporte de clasificación datos normalizados y 3 vecinos:")
print(classification_report(y_test, y_pred_scaled, target_names=["No Pagado", "Pagado"]))
print ("\nMatriz de confusión con datos normalizados y 3 vecinos:\n", confusion_matrix(y_test, y_pred_scaled), "\n")



Reporte de clasificación datos normalizados y 3 vecinos:
              precision    recall  f1-score   support

   No Pagado       0.23      0.12      0.16      1148
      Pagado       0.86      0.93      0.90      6683

    accuracy                           0.81      7831
   macro avg       0.55      0.53      0.53      7831
weighted avg       0.77      0.81      0.79      7831


Matriz de confusión con datos normalizados y 3 vecinos:
 [[ 135 1013]
 [ 448 6235]] 



In [22]:
#Modelo de Clasificación con datos normalizados y 5 vecinos
knn_scaled = KNeighborsClassifier(n_neighbors=5)
knn_scaled.fit(X_train_scaled, y_train)
y_pred_scaled = knn_scaled.predict(X_test_scaled)
print("\nReporte de clasificación datos normalizados y 5 vecinos:")
print(classification_report(y_test, y_pred_scaled, target_names=["No Pagado", "Pagado"]))
print ("\nMatriz de confusión con datos normalizados y 5 vecinos:\n", confusion_matrix(y_test, y_pred_scaled), "\n")


Reporte de clasificación datos normalizados y 5 vecinos:
              precision    recall  f1-score   support

   No Pagado       0.26      0.08      0.12      1148
      Pagado       0.86      0.96      0.91      6683

    accuracy                           0.83      7831
   macro avg       0.56      0.52      0.51      7831
weighted avg       0.77      0.83      0.79      7831


Matriz de confusión con datos normalizados y 5 vecinos:
 [[  90 1058]
 [ 257 6426]] 



In [26]:
#Modelo de Clasificación con datos normalizados y 10 vecinos
knn_scaled = KNeighborsClassifier(n_neighbors=10)
knn_scaled.fit(X_train_scaled, y_train)
y_pred_scaled = knn_scaled.predict(X_test_scaled)
print("\nReporte de clasificación datos normalizados y 10 vecinos:")
print(classification_report(y_test, y_pred_scaled, target_names=["No Pagado", "Pagado"]))
print ("\nMatriz de confusión con datos normalizados y 10 vecinos:\n", confusion_matrix(y_test, y_pred_scaled), "\n")


Reporte de clasificación datos normalizados y 10 vecinos:
              precision    recall  f1-score   support

   No Pagado       0.31      0.06      0.10      1148
      Pagado       0.86      0.98      0.91      6683

    accuracy                           0.84      7831
   macro avg       0.59      0.52      0.51      7831
weighted avg       0.78      0.84      0.79      7831


Matriz de confusión con datos normalizados y 10 vecinos:
 [[  66 1082]
 [ 145 6538]] 

